---
- hosts: localhost
  gather_facts: False 
  vars:
    roles_list:
      - vm_user         
      - deployer        
      - image_manager   
      - storage_manager 
      - vm_manager      
      - self_service      

  tasks:

  - name: listing all VMs
    os_server_info:
      cloud: devstack
      #filters:
      #  vm_state: active
    register: vm
    tags: deletevm

  - debug:
      msg: "{{ vm | json_query('openstack_servers[*].{name: name}')  }}"
    tags: deletevm

  - name: deleting all VMs and disks
    os_server:
      cloud: powervc10_snproject
      timeout: 900
      state: absent
      name: "{{ item.name }}"
      terminate_volume: no
      wait: yes
    tags: deletevm
    with_items :  "{{ vm | json_query('openstack_servers[*].{name: name}')  }}"

  - name: showing disks to delete
    debug:
      msg: "{{ vm | json_query('openstack_servers[*].{name: name, volumes: volumes} ')  }}"
    tags: deletevm

  - name: deleting disks
    os_volume:
      cloud: powervc10_snproject
      display_name:  "{{item}}"
      state: absent
      wait: no
    tags: deletedisks , deletevm 
    with_items: "{{ vm| json_query('openstack_servers[*].volumes[*].id') }}"
  
  - name: removing role from  project
    os_user_role:
      state: absent
      cloud: powervc10
      user: "{{ user_name }}"
      role: "{{ item }}"
      project: snproject
    loop: "{{ roles_list }}"

- hosts: RadarPowerVC
  gather_facts: False 
  user: root

  tasks:

  - name: deleting user
    user:
      state: absent 
      name: "{{ user_name }}"
      force: yes 
  
  - name: deleting home directory for user "{{ user_name }}"
    file: 
      path: "/home/{{ user_name }}"
      state: absent
  
- hosts: RadarLinuxVM
  gather_facts: False
  user: root

  tasks:

  - name: deleting 
    user:
      state: absent 
      name: "{{ user_name }}"
      force: yes 

  - name: deleting home directory for user "{{ user_name }}"
    file: 
      path: "/home/{{ user_name }}"
      state: absent
